# Generated by Django 6.0.3 on 2026-03-27 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('template_slug', models.CharField(choices=[('classic', 'Classic Professional'), ('modern', 'Modern Minimalist'), ('executive', 'Executive'), ('creative', 'Creative'), ('student', 'Student / Entry Level'), ('technical', 'Technical / Developer'), ('elegant', 'Elegant'), ('bold', 'Bold Impact'), ('clean', 'Clean ATS'), ('timeline', 'Timeline')], default='modern', max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('custom_css', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accent_color', models.CharField(default='#C9A84C', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('json', 'JSON')], max_length=10)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='resumes.resume')),
            ],
            options={
                'ordering': ['-exported_at'],
            },
        ),
    ]
